import esbuild from 'esbuild';
import { copyFile, mkdir } from 'node:fs/promises';
import { builtinModules } from 'node:module';
import process from 'node:process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Edit the TypeScript source instead of this file.
*/
`;

const production = process.argv[2] === 'production';

await mkdir('dist', { recursive: true });

const copyManifestPlugin = {
	name: 'copy-manifest',
	setup(build) {
		build.onStart(async () => {
			await copyFile('manifest.json', 'dist/manifest.json');
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: {
		main: 'src/main.ts',
		styles: 'styles.css',
	},
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	minify: production,
	outdir: 'dist',
	plugins: [copyManifestPlugin],
	sourcemap: production ? false : 'inline',
	treeShaking: true,
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
